### ISSUE TITLE
Use generic package manager module in streaming replication role

### ISSUE THREAD

**Issue by ruskofd** [ruskofd/postgresql-collection#7]
Use of DNF module in the following task is not correct :

```YAML
- name: Ensure 'psycopg2' package is installed (role dependency)
  ansible.builtin.dnf:
    name: python3-psycopg2
    state: present
```
should be

```YAML
- name: Ensure 'psycopg2' package is installed (role dependency)
  ansible.builtin.package:
    name: python3-psycopg2
    state: present
```
